nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://wepeak.vercel.app', 'http://localhost:5173','http://localhost:8000'] # Autoriser toutes les origines localhost
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
